name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build CSharp_Lab\CSharp_Lab.sln --no-restore
      #run: dotnet build --configuration Release --no-restore
      #- name: Test
      #run: dotnet test --configuration Release
      
